set tabstop=2
set softtabstop=2
set shiftwidth=2
"set smartindent
set autoindent
set expandtab
set number
set relativenumber
set nohlsearch
set wildmenu
set encoding=utf8
set hidden
set nowrap
set nocompatible
set noswapfile
set nobackup
set undodir=~/.config/nvim/undodir
set undofile
set splitbelow
set bl
set autoread
syn on
set mouse=a
set updatetime=300
let mapleader=" "
